import = [
"~/.config/alacritty/theme.toml",
"~/.config/alacritty/keybindings.toml",
]

[env]
TERM = "alacritty-direct"

[font]
size = 12.0

[font.bold]
family = "UDEV Gothic 35NFLG"
style = "Bold"

[font.italic]
family = "UDEV Gothic 35NFLG"
style = "Italic"

[font.normal]
family = "UDEV Gothic 35NFLG"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
startup_mode = "Maximized"
title = ""
